version: 2
updates:
  # yarn
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"