version: "3"
services:
    db:
        image: cockroachdb/cockroach
        ports:
            - 26257:26257
            - 8080:8080
        command: start-single-node --insecure
        volumes:
            - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
    redis:
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
