version: 2.1

jobs:
  Deploy Production:
    docker:
      - image: cimg/node:17.4.0
        environment:
          DATABASE_URL: $DATABASE_URL_PRODUCTION
          DOG_API_KEY: $DOG_API_KEY
          DOG_API_BASE_URL: $DOG_API_BASE_URL
          WEATHER_API_KEY: $WEATHER_API_KEY
          WEATHER_API_BASE_URL: $WEATHER_API_BASE_URL
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            echo 'export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')' >> $BASH_ENV
            echo 'export IMAGE_NAME=kmpw-api' >> $BASH_ENV
            echo DATABASE_URL="$DATABASE_URL" >> "${BASH_ENV}"
            echo DOG_API_KEY="$DOG_API_KEY" >> "${BASH_ENV}"
            echo DOG_API_BASE_URL="$DOG_API_BASE_URL" >> "${BASH_ENV}"
            echo WEATHER_API_KEY="$WEATHER_API_KEY" >> "${BASH_ENV}"
            echo WEATHER_API_BASE_URL="$WEATHER_API_BASE_URL" >> "${BASH_ENV}"
      - setup_remote_docker:
          version: 19.03.13
      # - run: 
      #     name: Install Dependencies
      #     command: yarn install
      # - run:
      #     name: Run Database Migrations
      #     command: yarn prisma:deploy
      # - run:
      #     name: Seed Database
      #     command: yarn prisma:seed
      - run:
          name: Build & Push Docker Image
          command: |
            docker build -t dylanolearydev/$IMAGE_NAME:$PACKAGE_VERSION .
            docker build -t dylanolearydev/$IMAGE_NAME:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push dylanolearydev/$IMAGE_NAME:$PACKAGE_VERSION
            docker push dylanolearydev/$IMAGE_NAME:latest
  Deploy Staging:
    docker:
      - image: cimg/node:17.4.0
        environment:
          DATABASE_URL: $DATABASE_URL_STAGING
          DOG_API_KEY: $DOG_API_KEY
          DOG_API_BASE_URL: $DOG_API_BASE_URL
          WEATHER_API_KEY: $WEATHER_API_KEY
          WEATHER_API_BASE_URL: $WEATHER_API_BASE_URL
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            echo 'export IMAGE_NAME=kmpw-api' >> $BASH_ENV
            echo DATABASE_URL="$DATABASE_URL" >> "${BASH_ENV}"
            echo DOG_API_KEY="$DOG_API_KEY" >> "${BASH_ENV}"
            echo DOG_API_BASE_URL="$DOG_API_BASE_URL" >> "${BASH_ENV}"
            echo WEATHER_API_KEY="$WEATHER_API_KEY" >> "${BASH_ENV}"
            echo WEATHER_API_BASE_URL="$WEATHER_API_BASE_URL" >> "${BASH_ENV}"
      - setup_remote_docker:
          version: 19.03.13
      # - run: 
      #     name: Install Dependencies
      #     command: yarn install
      # - run:
      #     name: Run Database Migrations
      #     command: yarn prisma:deploy
      # - run:
      #     name: Seed Database
      #     command: yarn prisma:seed
      - run:
          name: Build & Push Docker Image
          command: |
            docker build -t dylanolearydev/$IMAGE_NAME:staging .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push dylanolearydev/$IMAGE_NAME:staging

workflows:
  Deploy (Production):
    jobs:
      - Deploy Production:
          filters:
            branches:
              only:
                - main
  Deploy (Staging):
    jobs:
      - Deploy Staging:
          filters:
            branches:
              only:
                - staging
