options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
steps:
# Build the container image
- name: "gcr.io/cloud-builders/docker"
  id: Build API Image
  args:
  - "build"
  - "-t"
  - "us-east1-docker.pkg.dev/$PROJECT_ID/woxy-api/api:$SHORT_SHA"
  - "."

# Push the image to the artifact registry
- name: "gcr.io/cloud-builders/docker"
  id: Push API Image
  args:
  - "push"
  - "us-east1-docker.pkg.dev/$PROJECT_ID/woxy-api/api:$SHORT_SHA"

# Prepare the database – migrate & seed
- name: 'node'
  id: Install Dependencies
  entrypoint: 'yarn'
  args:
  - 'install'
- name: 'node'
  id: Generate Prisma Client
  entrypoint: 'yarn'
  args:
  - 'prisma:generate'
- name: 'node'
  id: Apply Prisma Migrations
  entrypoint: 'yarn'
  secretEnv:
  - 'DATABASE_URL'
  args:
  - 'prisma:migrate'
- name: 'node'
  id: Seed Prisma Database
  entrypoint: 'yarn'
  secretEnv: ['DATABASE_URL', 'DOG_API_KEY']
  env:
  - 'DOG_API_BASE_URL=https://api.thedogapi.com/v1'
  args: ['prisma:seed']

# Deploy the application using Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy Application
  args:
  - 'run'
  - 'deploy'
  - 'woxy-api'
  - '--allow-unauthenticated'
  - '--image=us-east1-docker.pkg.dev/$PROJECT_ID/woxy-api/api:$SHORT_SHA'
  - '--max-instances=3'
  - '--min-instances=1'
  - '--platform=managed'
  - '--region=us-east1'
  - '--revision-suffix=$SHORT_SHA'
  - '--tag=prod'
  - '--timeout=30s'
  # Env Config
  - '--set-env-vars=NODE_ENV=production'
  - '--set-env-vars=COMMIT_SHA=$SHORT_SHA'
  - '--set-env-vars=ACCESS_TOKEN_LIFESPAN=1d'
  - '--set-env-vars=AWS_REKOGNITION=1'
  - '--set-env-vars=AWS_REKOGNITION_REGION=us-east-1'
  - '--set-env-vars=CLOUDINARY_CLOUD_NAME=dhgpgb0yw'
  - '--set-env-vars=CLOUDINARY_FOLDER_PREFIX=kmpw'
  - '--set-env-vars=DOG_API_BASE_URL=https://api.thedogapi.com/v1'
  - '--set-env-vars=REFRESH_TOKEN_LIFESPAN=7d'
  - '--set-env-vars=SENTRY_ENABLED=1'
  - '--set-env-vars=SENTRY_SAMPLE_RATE=0.75'
  - '--set-env-vars=USER_MAX_NUM_OF_DOGS=5'
  - '--set-env-vars=WEATHER_API_BASE_URL=http://api.weatherapi.com/v1'
  - '--set-env-vars=WEATHER_API_MODERATE_ALERT_CODES='
  - '--set-env-vars=^##^WEATHER_API_SEVERE_ALERT_CODES=1063,1066,1069,1072,1087,1114,1117,1168,1171,1195,1201,1207,1219,1222,1225,1237,1246,1252,1258,1261,1264,1273,1276,1279,1282'
  - '--set-env-vars=WEATHER_CACHE_DISTANCE_METRES=5000'
  - '--set-env-vars=WEATHER_CACHE_LIFESPAN=5m'
  # Env Secrets
  - '--set-secrets=ACCESS_TOKEN_SECRET=ACCESS_TOKEN_SECRET:latest'
  - '--set-secrets=AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest'
  - '--set-secrets=AWS_SECRET_KEY=AWS_SECRET_KEY:latest'
  - '--set-secrets=CLOUDINARY_API_KEY=CLOUDINARY_API_KEY:latest'
  - '--set-secrets=CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET:latest'
  - '--set-secrets=DATABASE_URL=DATABASE_URL:latest'
  - '--set-secrets=DOG_API_KEY=DOG_API_KEY:latest'
  - '--set-secrets=REDIS_HOST=REDIS_HOST:latest'
  - '--set-secrets=REFRESH_TOKEN_SECRET=REFRESH_TOKEN_SECRET:latest'
  - '--set-secrets=SENTRY_DSN=SENTRY_DSN:latest'
  - '--set-secrets=WEATHER_API_KEY=WEATHER_API_KEY:latest'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
    env: 'DATABASE_URL'
  - versionName: projects/$PROJECT_ID/secrets/DOG_API_KEY/versions/latest
    env: 'DOG_API_KEY'
