steps:

# Build the container image
- name: "gcr.io/cloud-builders/docker"
  id: Build API Image
  args:
  - "build"
  - "-t"
  - "us-east1-docker.pkg.dev/$PROJECT_ID/woxy-api/api:$SHORT_SHA"
  - "."

# Push the image to the artifact registry
- name: "gcr.io/cloud-builders/docker"
  id: Push API Image
  args:
  - "push"
  - "us-east1-docker.pkg.dev/$PROJECT_ID/woxy-api/api:$SHORT_SHA"

- name: 'node'
  id: Install Dependencies
  entrypoint: 'yarn'
  args: ['install']

- name: 'node'
  id: Generate Prisma Client
  entrypoint: 'yarn'
  args: ['prisma:generate']

options:
  logging: CLOUD_LOGGING_ONLY
