name: Build and Deploy Application

env:
  pscale_base_directory: .pscale

on:
  push:
    branches:
    - feat/upstash

jobs:
  create-db-candidate-branch:
    extends: ./create-db-candidate-branch.yml
# trigger-cloudbuild:
#   runs-on: ubuntu-latest
#   steps:
#   - uses: actions/checkout@v2
#   - id: 'auth'
#     uses: 'google-github-actions/auth@v1'
#     with:
#       credentials_json: '${{ secrets.GCP_GITHUB_CLOUDBUILD_CREDENTIALS }}'
#   - name: 'Set up Cloud SDK'
#     uses: 'google-github-actions/setup-gcloud@v1'
#   - name: 'Use gcloud CLI'
#     run: 'gcloud info'
#   - name: 'Authenticate service account'
#     run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
#   - name: 'Start Google Cloud Build trigger'
#     run: |
#       export CLOUDSDK_CORE_DISABLE_PROMPTS=1
#       gcloud builds triggers run ${{ secrets.GCP_BUILD_API_IMAGE_TRIGGER_ID }}
