name: Build and Deploy Application

env:
  pscale_base_directory: .pscale

on:
  push:
    branches:
    - feat/upstash

jobs:
  prepare-db:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: main-candidate
      DB_NAME: woxy
      GITHUB_USER: ${{ github.actor }}
      ORG_NAME: dylanolearydev
      PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create candidate DB branch
      id: create-db-candidate-branch
      timeout-minutes: 3
      working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
      run: |
        ./create-branch.sh "$BRANCH_NAME"
    - name: Delete candidate DB branch
      id: delete-candidate-db-branch
      timeout-minutes: 3
      working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
      run: |
        ./delete-branch.sh "$BRANCH_NAME"

# trigger-cloudbuild:
#   runs-on: ubuntu-latest
#   steps:
#   - uses: actions/checkout@v2
#   - id: 'auth'
#     uses: 'google-github-actions/auth@v1'
#     with:
#       credentials_json: '${{ secrets.GCP_GITHUB_CLOUDBUILD_CREDENTIALS }}'
#   - name: 'Set up Cloud SDK'
#     uses: 'google-github-actions/setup-gcloud@v1'
#   - name: 'Use gcloud CLI'
#     run: 'gcloud info'
#   - name: 'Authenticate service account'
#     run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
#   - name: 'Start Google Cloud Build trigger'
#     run: |
#       export CLOUDSDK_CORE_DISABLE_PROMPTS=1
#       gcloud builds triggers run ${{ secrets.GCP_BUILD_API_IMAGE_TRIGGER_ID }}
